//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.Resume = new HashSet<Resume>();
        }
    
        public int Id { get; set; }
        public byte[] Resim { get; set; }
    
        public virtual ICollection<Resume> Resume { get; set; }
    }
}
